// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cities.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createCity = `-- name: CreateCity :one
INSERT INTO cities ( city, state)
VALUES ( $1, $2 )
RETURNING id, city, state
`

type CreateCityParams struct {
	City  string `json:"city"`
	State string `json:"state"`
}

type CreateCityRow struct {
	ID    uuid.UUID `json:"id"`
	City  string    `json:"city"`
	State string    `json:"state"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (CreateCityRow, error) {
	row := q.db.QueryRow(ctx, createCity, arg.City, arg.State)
	var i CreateCityRow
	err := row.Scan(&i.ID, &i.City, &i.State)
	return i, err
}

const deleteCityById = `-- name: DeleteCityById :execrows
DELETE FROM cities
WHERE id = $1
`

func (q *Queries) DeleteCityById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCityById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllCities = `-- name: GetAllCities :many
SELECT id, city, state FROM cities
`

type GetAllCitiesRow struct {
	ID    uuid.UUID `json:"id"`
	City  string    `json:"city"`
	State string    `json:"state"`
}

func (q *Queries) GetAllCities(ctx context.Context) ([]GetAllCitiesRow, error) {
	rows, err := q.db.Query(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCitiesRow
	for rows.Next() {
		var i GetAllCitiesRow
		if err := rows.Scan(&i.ID, &i.City, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCityById = `-- name: GetCityById :one
SELECT city, state FROM cities
WHERE id = $1
`

type GetCityByIdRow struct {
	City  string `json:"city"`
	State string `json:"state"`
}

func (q *Queries) GetCityById(ctx context.Context, id uuid.UUID) (GetCityByIdRow, error) {
	row := q.db.QueryRow(ctx, getCityById, id)
	var i GetCityByIdRow
	err := row.Scan(&i.City, &i.State)
	return i, err
}
