// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
insert into
  movies (
    name,
    description,
    casts,
    trailer_url,
    languages,
    release_date,
    director,
    status
  )
values
  ( $1, $2, $3, $4, $5, $6, $7, $8) 
returning id
`

type CreateMovieParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Name,
		arg.Description,
		arg.Casts,
		arg.TrailerUrl,
		arg.Languages,
		arg.ReleaseDate,
		arg.Director,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteMovieById = `-- name: DeleteMovieById :exec
delete from movies
where id = $1
`

func (q *Queries) DeleteMovieById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMovieById, id)
	return err
}

const getMovieById = `-- name: GetMovieById :one
select
  id, name, description, casts, trailer_url, languages, release_date, director, status
from movies
where id = $1
`

type GetMovieByIdRow struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (GetMovieByIdRow, error) {
	row := q.db.QueryRow(ctx, getMovieById, id)
	var i GetMovieByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Casts,
		&i.TrailerUrl,
		&i.Languages,
		&i.ReleaseDate,
		&i.Director,
		&i.Status,
	)
	return i, err
}

const updateMovieById = `-- name: UpdateMovieById :one
UPDATE movies SET 
  name = coalesce($2, name),
  description = coalesce($3, description),
  casts = coalesce($4, casts),
  trailer_url = coalesce($5, trailer_url),
  languages = coalesce($6, languages),
  release_date = coalesce($7, release_date),
  director = coalesce($8, director),
  status = coalesce($9, status),
  updated_at = NOW()
WHERE id = $1
returning
  name, description, casts, trailer_url, languages, release_date, director, status
`

type UpdateMovieByIdParams struct {
	ID          uuid.UUID          `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	Casts       []string           `json:"casts"`
	TrailerUrl  pgtype.Text        `json:"trailer_url"`
	Languages   []string           `json:"languages"`
	ReleaseDate pgtype.Timestamptz `json:"release_date"`
	Director    pgtype.Text        `json:"director"`
	Status      NullReleaseStatus  `json:"status"`
}

type UpdateMovieByIdRow struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) UpdateMovieById(ctx context.Context, arg UpdateMovieByIdParams) (UpdateMovieByIdRow, error) {
	row := q.db.QueryRow(ctx, updateMovieById,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Casts,
		arg.TrailerUrl,
		arg.Languages,
		arg.ReleaseDate,
		arg.Director,
		arg.Status,
	)
	var i UpdateMovieByIdRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Casts,
		&i.TrailerUrl,
		&i.Languages,
		&i.ReleaseDate,
		&i.Director,
		&i.Status,
	)
	return i, err
}
