// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (uuid.UUID, error)
	DeleteMovieById(ctx context.Context, id uuid.UUID) error
	GetMovieById(ctx context.Context, id uuid.UUID) (GetMovieByIdRow, error)
	UpdateMovieById(ctx context.Context, arg UpdateMovieByIdParams) (UpdateMovieByIdRow, error)
}

var _ Querier = (*Queries)(nil)
