// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: theaters.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTheater = `-- name: CreateTheater :one
INSERT INTO theaters (
  name, description, city_id, address, pincode
) VALUES ($1, $2, $3, $4, $5)
RETURNING 
  id, name, description, city_id, address, pincode
`

type CreateTheaterParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CityID      uuid.UUID `json:"city_id"`
	Address     string    `json:"address"`
	Pincode     string    `json:"pincode"`
}

type CreateTheaterRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CityID      uuid.UUID `json:"city_id"`
	Address     string    `json:"address"`
	Pincode     string    `json:"pincode"`
}

func (q *Queries) CreateTheater(ctx context.Context, arg CreateTheaterParams) (CreateTheaterRow, error) {
	row := q.db.QueryRow(ctx, createTheater,
		arg.Name,
		arg.Description,
		arg.CityID,
		arg.Address,
		arg.Pincode,
	)
	var i CreateTheaterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Address,
		&i.Pincode,
	)
	return i, err
}

const deleteTheaterById = `-- name: DeleteTheaterById :execrows
DELETE FROM theaters
WHERE id = $1
`

func (q *Queries) DeleteTheaterById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTheaterById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllTheaters = `-- name: GetAllTheaters :many
SELECT 
  id,
  name,
  description,
  city_id,
  address,
  pincode
FROM theaters
`

type GetAllTheatersRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CityID      uuid.UUID `json:"city_id"`
	Address     string    `json:"address"`
	Pincode     string    `json:"pincode"`
}

func (q *Queries) GetAllTheaters(ctx context.Context) ([]GetAllTheatersRow, error) {
	rows, err := q.db.Query(ctx, getAllTheaters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTheatersRow
	for rows.Next() {
		var i GetAllTheatersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CityID,
			&i.Address,
			&i.Pincode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTheatersByCityId = `-- name: GetTheatersByCityId :many
SELECT 
  id,
  name,
  description,
  city_id,
  address,
  pincode
FROM theaters
WHERE city_id = $1
`

type GetTheatersByCityIdRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CityID      uuid.UUID `json:"city_id"`
	Address     string    `json:"address"`
	Pincode     string    `json:"pincode"`
}

func (q *Queries) GetTheatersByCityId(ctx context.Context, cityID uuid.UUID) ([]GetTheatersByCityIdRow, error) {
	rows, err := q.db.Query(ctx, getTheatersByCityId, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTheatersByCityIdRow
	for rows.Next() {
		var i GetTheatersByCityIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CityID,
			&i.Address,
			&i.Pincode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTheatersById = `-- name: GetTheatersById :one
SELECT 
  id,
  name,
  description,
  city_id,
  address,
  pincode
FROM theaters
WHERE id = $1
`

type GetTheatersByIdRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CityID      uuid.UUID `json:"city_id"`
	Address     string    `json:"address"`
	Pincode     string    `json:"pincode"`
}

func (q *Queries) GetTheatersById(ctx context.Context, id uuid.UUID) (GetTheatersByIdRow, error) {
	row := q.db.QueryRow(ctx, getTheatersById, id)
	var i GetTheatersByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Address,
		&i.Pincode,
	)
	return i, err
}

const updateTheatreById = `-- name: UpdateTheatreById :one
UPDATE theaters SET
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  city_id = COALESCE($4, city_id),
  address = COALESCE($5, address),
  pincode = COALESCE($6, pincode),
  updated_at = NOW()
WHERE id = $1
RETURNING 
  id, name, description, city_id, address, pincode
`

type UpdateTheatreByIdParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	CityID      pgtype.UUID `json:"city_id"`
	Address     pgtype.Text `json:"address"`
	Pincode     pgtype.Text `json:"pincode"`
}

type UpdateTheatreByIdRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CityID      uuid.UUID `json:"city_id"`
	Address     string    `json:"address"`
	Pincode     string    `json:"pincode"`
}

func (q *Queries) UpdateTheatreById(ctx context.Context, arg UpdateTheatreByIdParams) (UpdateTheatreByIdRow, error) {
	row := q.db.QueryRow(ctx, updateTheatreById,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CityID,
		arg.Address,
		arg.Pincode,
	)
	var i UpdateTheatreByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CityID,
		&i.Address,
		&i.Pincode,
	)
	return i, err
}
