// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ReleaseStatus string

const (
	ReleaseStatusRELEASED   ReleaseStatus = "RELEASED"
	ReleaseStatusUNRELEASED ReleaseStatus = "UNRELEASED"
	ReleaseStatusBLOCKED    ReleaseStatus = "BLOCKED"
)

func (e *ReleaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReleaseStatus(s)
	case string:
		*e = ReleaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReleaseStatus: %T", src)
	}
	return nil
}

type NullReleaseStatus struct {
	ReleaseStatus ReleaseStatus `json:"release_status"`
	Valid         bool          `json:"valid"` // Valid is true if ReleaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReleaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReleaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReleaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReleaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReleaseStatus), nil
}

type City struct {
	ID        uuid.UUID          `json:"id"`
	City      string             `json:"city"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Movie struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Casts       []string           `json:"casts"`
	TrailerUrl  string             `json:"trailer_url"`
	Languages   []string           `json:"languages"`
	ReleaseDate time.Time          `json:"release_date"`
	Director    string             `json:"director"`
	Status      ReleaseStatus      `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	NameTsv     interface{}        `json:"name_tsv"`
}

type Screen struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	TheaterID  uuid.UUID          `json:"theater_id"`
	TotalSeats int32              `json:"total_seats"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Show struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movie_id"`
	ScreenID  uuid.UUID `json:"screen_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Theater struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CityID      uuid.UUID          `json:"city_id"`
	Address     string             `json:"address"`
	Pincode     string             `json:"pincode"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
