// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO
  movies (
    name,
    description,
    casts,
    trailer_url,
    languages,
    release_date,
    director,
    status
  )
VALUES
  ( $1, $2, $3, $4, $5, $6, $7, $8) 
RETURNING 
  id, name, description, casts, trailer_url, languages, release_date, director, status
`

type CreateMovieParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

type CreateMovieRow struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (CreateMovieRow, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Name,
		arg.Description,
		arg.Casts,
		arg.TrailerUrl,
		arg.Languages,
		arg.ReleaseDate,
		arg.Director,
		arg.Status,
	)
	var i CreateMovieRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Casts,
		&i.TrailerUrl,
		&i.Languages,
		&i.ReleaseDate,
		&i.Director,
		&i.Status,
	)
	return i, err
}

const deleteMovieById = `-- name: DeleteMovieById :execrows
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovieById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovieById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAiringMovies = `-- name: GetAiringMovies :many
SELECT 
  m.name, m.description, casts, trailer_url, languages, release_date, director, status
FROM movies m
JOIN shows s on s.movie_id = m.id
JOIN screens sc on sc.id = s.screen_id
JOIN theaters t ON t.id = sc.theater_id
JOIN cities c ON c.id = t.city_id
WHERE
  c.id = $1 AND
  s.start_time >= NOW() AND
  s.end_time < (CURRENT_DATE + INTERVAL '1 day')
`

type GetAiringMoviesRow struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) GetAiringMovies(ctx context.Context, cityID uuid.UUID) ([]GetAiringMoviesRow, error) {
	rows, err := q.db.Query(ctx, getAiringMovies, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAiringMoviesRow
	for rows.Next() {
		var i GetAiringMoviesRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Casts,
			&i.TrailerUrl,
			&i.Languages,
			&i.ReleaseDate,
			&i.Director,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMovies = `-- name: GetAllMovies :many
SELECT 
  name, description, casts, trailer_url, languages, release_date, director, status
FROM movies
`

type GetAllMoviesRow struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) GetAllMovies(ctx context.Context) ([]GetAllMoviesRow, error) {
	rows, err := q.db.Query(ctx, getAllMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMoviesRow
	for rows.Next() {
		var i GetAllMoviesRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Casts,
			&i.TrailerUrl,
			&i.Languages,
			&i.ReleaseDate,
			&i.Director,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieById = `-- name: GetMovieById :one
SELECT
  id, name, description, casts, trailer_url, languages, release_date, director, status
FROM movies
WHERE id = $1
`

type GetMovieByIdRow struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (GetMovieByIdRow, error) {
	row := q.db.QueryRow(ctx, getMovieById, id)
	var i GetMovieByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Casts,
		&i.TrailerUrl,
		&i.Languages,
		&i.ReleaseDate,
		&i.Director,
		&i.Status,
	)
	return i, err
}

const getUpcomingMovies = `-- name: GetUpcomingMovies :many
SELECT 
  name, description, casts, trailer_url, languages, release_date, director, status
FROM movies
WHERE release_date > NOW()
`

type GetUpcomingMoviesRow struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) GetUpcomingMovies(ctx context.Context) ([]GetUpcomingMoviesRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingMoviesRow
	for rows.Next() {
		var i GetUpcomingMoviesRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Casts,
			&i.TrailerUrl,
			&i.Languages,
			&i.ReleaseDate,
			&i.Director,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovieById = `-- name: UpdateMovieById :one
UPDATE movies SET 
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  casts = COALESCE($4, casts),
  trailer_url = COALESCE($5, trailer_url),
  languages = COALESCE($6, languages),
  release_date = COALESCE($7, release_date),
  director = COALESCE($8, director),
  status = COALESCE($9, status),
  updated_at = NOW()
WHERE id = $1
RETURNING
  name, description, casts, trailer_url, languages, release_date, director, status
`

type UpdateMovieByIdParams struct {
	ID          uuid.UUID          `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	Casts       []string           `json:"casts"`
	TrailerUrl  pgtype.Text        `json:"trailer_url"`
	Languages   []string           `json:"languages"`
	ReleaseDate pgtype.Timestamptz `json:"release_date"`
	Director    pgtype.Text        `json:"director"`
	Status      NullReleaseStatus  `json:"status"`
}

type UpdateMovieByIdRow struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Casts       []string      `json:"casts"`
	TrailerUrl  string        `json:"trailer_url"`
	Languages   []string      `json:"languages"`
	ReleaseDate time.Time     `json:"release_date"`
	Director    string        `json:"director"`
	Status      ReleaseStatus `json:"status"`
}

func (q *Queries) UpdateMovieById(ctx context.Context, arg UpdateMovieByIdParams) (UpdateMovieByIdRow, error) {
	row := q.db.QueryRow(ctx, updateMovieById,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Casts,
		arg.TrailerUrl,
		arg.Languages,
		arg.ReleaseDate,
		arg.Director,
		arg.Status,
	)
	var i UpdateMovieByIdRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Casts,
		&i.TrailerUrl,
		&i.Languages,
		&i.ReleaseDate,
		&i.Director,
		&i.Status,
	)
	return i, err
}
