// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCity(ctx context.Context, arg CreateCityParams) (CreateCityRow, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (CreateMovieRow, error)
	CreateScreen(ctx context.Context, arg CreateScreenParams) (CreateScreenRow, error)
	CreateShow(ctx context.Context, arg CreateShowParams) (CreateShowRow, error)
	CreateTheater(ctx context.Context, arg CreateTheaterParams) (CreateTheaterRow, error)
	DeleteCityById(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMovieById(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteScreenByID(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteShowById(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteTheaterById(ctx context.Context, id uuid.UUID) (int64, error)
	GetAllCities(ctx context.Context) ([]GetAllCitiesRow, error)
	GetAllMovies(ctx context.Context) ([]GetAllMoviesRow, error)
	GetAllScreensByTheaterId(ctx context.Context, theaterID uuid.UUID) ([]GetAllScreensByTheaterIdRow, error)
	GetAllTheaters(ctx context.Context) ([]GetAllTheatersRow, error)
	GetCityById(ctx context.Context, id uuid.UUID) (GetCityByIdRow, error)
	GetMovieById(ctx context.Context, id uuid.UUID) (GetMovieByIdRow, error)
	GetMoviesByName(ctx context.Context, websearchToTsquery string) ([]GetMoviesByNameRow, error)
	GetScreenById(ctx context.Context, id uuid.UUID) (GetScreenByIdRow, error)
	GetShowInfoById(ctx context.Context, arg GetShowInfoByIdParams) (GetShowInfoByIdRow, error)
	GetShowsByMovieBetweenTimeRange(ctx context.Context, arg GetShowsByMovieBetweenTimeRangeParams) ([]GetShowsByMovieBetweenTimeRangeRow, error)
	GetShowsByMovieId(ctx context.Context, arg GetShowsByMovieIdParams) ([]GetShowsByMovieIdRow, error)
	GetShowsByTheaterId(ctx context.Context, arg GetShowsByTheaterIdParams) ([]GetShowsByTheaterIdRow, error)
	GetTheatersByCityId(ctx context.Context, cityID uuid.UUID) ([]GetTheatersByCityIdRow, error)
	GetTheatersById(ctx context.Context, id uuid.UUID) (GetTheatersByIdRow, error)
	GetUpcomingMovies(ctx context.Context, cityID uuid.UUID) ([]GetUpcomingMoviesRow, error)
	GetUpcomingMoviesInTheater(ctx context.Context, arg GetUpcomingMoviesInTheaterParams) ([]GetUpcomingMoviesInTheaterRow, error)
	UpdateMovieById(ctx context.Context, arg UpdateMovieByIdParams) (UpdateMovieByIdRow, error)
	UpdateScreenById(ctx context.Context, arg UpdateScreenByIdParams) (UpdateScreenByIdRow, error)
	UpdateShowById(ctx context.Context, arg UpdateShowByIdParams) (UpdateShowByIdRow, error)
	UpdateTheatreById(ctx context.Context, arg UpdateTheatreByIdParams) (UpdateTheatreByIdRow, error)
}

var _ Querier = (*Queries)(nil)
