// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screens.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScreen = `-- name: CreateScreen :one
INSERT INTO screens 
  (name, theater_id, total_seats)
VALUES 
  ( $1, $2, $3 )
RETURNING 
  id, name, total_seats, theater_id
`

type CreateScreenParams struct {
	Name       string    `json:"name"`
	TheaterID  uuid.UUID `json:"theater_id"`
	TotalSeats int32     `json:"total_seats"`
}

type CreateScreenRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	TotalSeats int32     `json:"total_seats"`
	TheaterID  uuid.UUID `json:"theater_id"`
}

func (q *Queries) CreateScreen(ctx context.Context, arg CreateScreenParams) (CreateScreenRow, error) {
	row := q.db.QueryRow(ctx, createScreen, arg.Name, arg.TheaterID, arg.TotalSeats)
	var i CreateScreenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalSeats,
		&i.TheaterID,
	)
	return i, err
}

const deleteScreenByID = `-- name: DeleteScreenByID :execrows
DELETE FROM screens
WHERE id = $1
`

func (q *Queries) DeleteScreenByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScreenByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllScreensByTheaterId = `-- name: GetAllScreensByTheaterId :many
SELECT id, name, total_seats, theater_id
FROM screens
WHERE theater_id = $1
`

type GetAllScreensByTheaterIdRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	TotalSeats int32     `json:"total_seats"`
	TheaterID  uuid.UUID `json:"theater_id"`
}

func (q *Queries) GetAllScreensByTheaterId(ctx context.Context, theaterID uuid.UUID) ([]GetAllScreensByTheaterIdRow, error) {
	rows, err := q.db.Query(ctx, getAllScreensByTheaterId, theaterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllScreensByTheaterIdRow
	for rows.Next() {
		var i GetAllScreensByTheaterIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalSeats,
			&i.TheaterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScreenById = `-- name: GetScreenById :one
SELECT id, name, total_seats, theater_id
FROM screens
WHERE id = $1
`

type GetScreenByIdRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	TotalSeats int32     `json:"total_seats"`
	TheaterID  uuid.UUID `json:"theater_id"`
}

func (q *Queries) GetScreenById(ctx context.Context, id uuid.UUID) (GetScreenByIdRow, error) {
	row := q.db.QueryRow(ctx, getScreenById, id)
	var i GetScreenByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalSeats,
		&i.TheaterID,
	)
	return i, err
}

const updateScreenById = `-- name: UpdateScreenById :one
UPDATE screens SET
  name = COALESCE($2, name),
  theater_id = COALESCE($3, theater_id),
  total_seats = COALESCE($4, total_seats)
WHERE id = $1
RETURNING
  id, name, total_seats, theater_id
`

type UpdateScreenByIdParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       pgtype.Text `json:"name"`
	TheaterID  pgtype.UUID `json:"theater_id"`
	TotalSeats pgtype.Int4 `json:"total_seats"`
}

type UpdateScreenByIdRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	TotalSeats int32     `json:"total_seats"`
	TheaterID  uuid.UUID `json:"theater_id"`
}

func (q *Queries) UpdateScreenById(ctx context.Context, arg UpdateScreenByIdParams) (UpdateScreenByIdRow, error) {
	row := q.db.QueryRow(ctx, updateScreenById,
		arg.ID,
		arg.Name,
		arg.TheaterID,
		arg.TotalSeats,
	)
	var i UpdateScreenByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalSeats,
		&i.TheaterID,
	)
	return i, err
}
