// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shows.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShow = `-- name: CreateShow :one
INSERT INTO shows 
  ( movie_id, screen_id, start_time, end_time )
VALUES 
  ( $1, $2, $3, $4 )
RETURNING 
  id, movie_id, screen_id, start_time, end_time
`

type CreateShowParams struct {
	MovieID   uuid.UUID `json:"movie_id"`
	ScreenID  uuid.UUID `json:"screen_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type CreateShowRow struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movie_id"`
	ScreenID  uuid.UUID `json:"screen_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) CreateShow(ctx context.Context, arg CreateShowParams) (CreateShowRow, error) {
	row := q.db.QueryRow(ctx, createShow,
		arg.MovieID,
		arg.ScreenID,
		arg.StartTime,
		arg.EndTime,
	)
	var i CreateShowRow
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.ScreenID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteShowById = `-- name: DeleteShowById :execrows
DELETE FROM shows
WHERE id = $1
`

func (q *Queries) DeleteShowById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShowById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShowInfoById = `-- name: GetShowInfoById :one
SELECT 
  s.id,
  s.start_time,
  s.end_time,
  s.screen_id,
  s.movie_id,
  m.name AS movie_name,
  sc.name AS screen_name,
  sc.id AS screen_id,
  t.id AS theater_id,
  t.name AS theater_name
FROM shows s
JOIN movies m ON m.id = s.movie_id
JOIN screens sc ON sc.id = s.screen_id
JOIN theaters t ON t.id = sc.theater_id
WHERE s.id = $1
`

type GetShowInfoByIdRow struct {
	ID          uuid.UUID `json:"id"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	ScreenID    uuid.UUID `json:"screen_id"`
	MovieID     uuid.UUID `json:"movie_id"`
	MovieName   string    `json:"movie_name"`
	ScreenName  string    `json:"screen_name"`
	ScreenID_2  uuid.UUID `json:"screen_id_2"`
	TheaterID   uuid.UUID `json:"theater_id"`
	TheaterName string    `json:"theater_name"`
}

func (q *Queries) GetShowInfoById(ctx context.Context, id uuid.UUID) (GetShowInfoByIdRow, error) {
	row := q.db.QueryRow(ctx, getShowInfoById, id)
	var i GetShowInfoByIdRow
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.ScreenID,
		&i.MovieID,
		&i.MovieName,
		&i.ScreenName,
		&i.ScreenID_2,
		&i.TheaterID,
		&i.TheaterName,
	)
	return i, err
}

const getShowsByCityId = `-- name: GetShowsByCityId :many
SELECT 
  m.id AS movie_id,
  m.name AS movie_name,
  sc.id AS screen_id,
  sc.name AS screen_name,
  s.id AS show_id,
  s.start_time,
  s.end_time,
  t.id AS theater_id,
  t.name AS theater_name
FROM shows s
JOIN movies m ON m.id = s.movie_id
JOIN screens sc ON sc.id = s.screen_id
JOIN theaters t ON t.id = sc.theater_id
JOIN cities c ON c.id = t.city_id
WHERE 
  c.id = $1 AND
  s.start_time > NOW()
`

type GetShowsByCityIdRow struct {
	MovieID     uuid.UUID `json:"movie_id"`
	MovieName   string    `json:"movie_name"`
	ScreenID    uuid.UUID `json:"screen_id"`
	ScreenName  string    `json:"screen_name"`
	ShowID      uuid.UUID `json:"show_id"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	TheaterID   uuid.UUID `json:"theater_id"`
	TheaterName string    `json:"theater_name"`
}

func (q *Queries) GetShowsByCityId(ctx context.Context, cityID uuid.UUID) ([]GetShowsByCityIdRow, error) {
	rows, err := q.db.Query(ctx, getShowsByCityId, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsByCityIdRow
	for rows.Next() {
		var i GetShowsByCityIdRow
		if err := rows.Scan(
			&i.MovieID,
			&i.MovieName,
			&i.ScreenID,
			&i.ScreenName,
			&i.ShowID,
			&i.StartTime,
			&i.EndTime,
			&i.TheaterID,
			&i.TheaterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsByMovieId = `-- name: GetShowsByMovieId :many
SELECT
  s.id,
  s.start_time,
  s.end_time,
  s.screen_id,
  m.name AS movie_name,
  sc.name AS screen_name,
  sc.id AS screen_id,
  t.id AS theater_id,
  t.name AS theater_name
FROM movies m
JOIN shows s ON s.movie_id = m.id
JOIN screens sc ON sc.id = s.screen_id
JOIN theaters t ON t.id = sc.theater_id
JOIN cities c ON c.id = t.city_id
WHERE 
  c.id = $1 AND
  m.id = $2 AND
  s.start_time > NOW()
`

type GetShowsByMovieIdParams struct {
	CityID  uuid.UUID `json:"city_id"`
	MovieID uuid.UUID `json:"movie_id"`
}

type GetShowsByMovieIdRow struct {
	ID          uuid.UUID `json:"id"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	ScreenID    uuid.UUID `json:"screen_id"`
	MovieName   string    `json:"movie_name"`
	ScreenName  string    `json:"screen_name"`
	ScreenID_2  uuid.UUID `json:"screen_id_2"`
	TheaterID   uuid.UUID `json:"theater_id"`
	TheaterName string    `json:"theater_name"`
}

func (q *Queries) GetShowsByMovieId(ctx context.Context, arg GetShowsByMovieIdParams) ([]GetShowsByMovieIdRow, error) {
	rows, err := q.db.Query(ctx, getShowsByMovieId, arg.CityID, arg.MovieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsByMovieIdRow
	for rows.Next() {
		var i GetShowsByMovieIdRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.ScreenID,
			&i.MovieName,
			&i.ScreenName,
			&i.ScreenID_2,
			&i.TheaterID,
			&i.TheaterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsByTheaterId = `-- name: GetShowsByTheaterId :many
SELECT 
  m.id AS movie_id,
  m.name AS movie_name,
  sc.id AS screen_id,
  sc.name AS screen_name,
  t.name AS theater_name,
  s.id AS show_id,
  s.start_time,
  s.end_time
FROM shows s
JOIN movies m ON m.id = s.movie_id
JOIN screens sc ON sc.id = s.screen_id
JOIN theaters t ON t.id = sc.theater_id
WHERE 
  t.id = $1 AND
  s.start_time > NOW()
`

type GetShowsByTheaterIdRow struct {
	MovieID     uuid.UUID `json:"movie_id"`
	MovieName   string    `json:"movie_name"`
	ScreenID    uuid.UUID `json:"screen_id"`
	ScreenName  string    `json:"screen_name"`
	TheaterName string    `json:"theater_name"`
	ShowID      uuid.UUID `json:"show_id"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
}

func (q *Queries) GetShowsByTheaterId(ctx context.Context, theaterID uuid.UUID) ([]GetShowsByTheaterIdRow, error) {
	rows, err := q.db.Query(ctx, getShowsByTheaterId, theaterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsByTheaterIdRow
	for rows.Next() {
		var i GetShowsByTheaterIdRow
		if err := rows.Scan(
			&i.MovieID,
			&i.MovieName,
			&i.ScreenID,
			&i.ScreenName,
			&i.TheaterName,
			&i.ShowID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShowById = `-- name: UpdateShowById :one
UPDATE shows SET 
  movie_id = COALESCE($2, movie_id),
  screen_id = COALESCE($3, screen_id),
  start_time = COALESCE($4, start_time),
  end_time = COALESCE($5, end_time)
WHERE 
  id = $1
RETURNING
  id, movie_id, screen_id, start_time, end_time
`

type UpdateShowByIdParams struct {
	ID        uuid.UUID          `json:"id"`
	MovieID   pgtype.UUID        `json:"movie_id"`
	ScreenID  pgtype.UUID        `json:"screen_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type UpdateShowByIdRow struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movie_id"`
	ScreenID  uuid.UUID `json:"screen_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) UpdateShowById(ctx context.Context, arg UpdateShowByIdParams) (UpdateShowByIdRow, error) {
	row := q.db.QueryRow(ctx, updateShowById,
		arg.ID,
		arg.MovieID,
		arg.ScreenID,
		arg.StartTime,
		arg.EndTime,
	)
	var i UpdateShowByIdRow
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.ScreenID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
